// =============================================================
// TanStack Router instance
//
// The routeTree is auto-generated by @tanstack/router-plugin
// from the files in src/routes/.
//
// Run `bun run dev` once and the plugin will generate
// src/routeTree.gen.ts automatically.
// =============================================================

import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

export const router = createRouter({
  routeTree,
  defaultPreload: "intent",
  scrollRestoration: true,
});

// Register router type for type-safe navigation across the app
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
